services:
  db:
    image: postgres:15-alpine
    container_name: langueschool_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-langueschool_db}
      POSTGRES_USER: ${DB_USER:-langueschool_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-M.g.4646}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - langueschool_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-langueschool_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: langueschool_backend
    restart: always
    env_file:
      - ./backend/languageschool/.env
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - langueschool_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: langueschool_frontend
    restart: always
    env_file:
      - ./frontend/.env
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - langueschool_net

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: langueschool_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - langueschool_net

volumes:
  postgres_data:

networks:
  langueschool_net:
    driver: bridge

