# Generated by Django 5.2.9 on 2026-03-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_end_date_course_end_time_course_quota_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="education_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
