# Generated by Django 5.2.9 on 2026-03-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_education_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_oid",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ödeme Bekliyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Hatalı"),
                            ("refunded", "İade Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("refund_requested", models.BooleanField(default=False)),
                ("refund_reason", models.TextField(blank=True, null=True)),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("none", "Talep Yok"),
                            ("pending", "Beklemede"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Order",
                "verbose_name_plural": "Course Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
