# Generated by Django 5.2.9 on 2026-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_courseorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Yakında Başlayacak"),
                    ("ongoing", "Devam Ediyor"),
                    ("completed", "Tamamlandı"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
