# Generated by Django 5.2.9 on 2026-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelexam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
