# Generated by Django 5.2.9 on 2026-03-13 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_course_first_day_course_last_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image_public_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        default="A1",
                        max_length=2,
                    ),
                ),
                ("quota", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "education_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("first_day", models.CharField(blank=True, max_length=20, null=True)),
                ("last_day", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Yakında Başlayacak"),
                            ("ongoing", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="private_lesson",
                        to="courses.coursecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivateLessonOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_oid",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ödeme Bekliyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Hatalı"),
                            ("refund_requested", "İade Talep Edildi"),
                            ("refunded", "İade Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("refund_requested", models.BooleanField(default=False)),
                ("refund_reason", models.TextField(blank=True, null=True)),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("none", "Talep Yok"),
                            ("pending", "Beklemede"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "private_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="courses.privatelesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="private_lesson_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Private Lesson Order",
                "verbose_name_plural": "Private Lesson Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivateLessonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "private_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="courses.privatelesson",
                    ),
                ),
            ],
        ),
    ]
