# Generated by Django 5.2.9 on 2026-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_courseorder_is_link_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("private", "Private"),
                    ("face_to_face", "Yüz Yüze"),
                ],
                default="online",
                max_length=20,
            ),
        ),
    ]
