# Generated by Django 5.2.9 on 2026-02-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
