# Generated by Django 5.2.9 on 2026-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_blogpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="category_posts", to="blog.category"
            ),
        ),
    ]
