# Generated by Django 5.2.9 on 2026-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blogpost_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
