# Generated by Django 5.2.9 on 2026-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
