# Generated by Django 5.2.9 on 2026-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_users_deleted_at_users_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                (
                    "author_avatar_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("review_text", models.TextField()),
                ("review_date", models.CharField(max_length=100)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("author_name", "review_text")},
            },
        ),
    ]
