# Generated by Django 5.2.9 on 2026-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_googlereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
