# Generated by Django 5.2.9 on 2026-03-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_users_address_users_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Video Başlığı"),
                ),
                (
                    "youtube_url",
                    models.URLField(max_length=500, verbose_name="YouTube Linki"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "YouTube Linki",
                "verbose_name_plural": "YouTube Linkleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
