# Generated by Django 5.2.9 on 2026-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_youtubelink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubelink",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "YouTube Link",
                "verbose_name_plural": "YouTube Links",
            },
        ),
        migrations.AlterField(
            model_name="youtubelink",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="youtubelink",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="youtubelink",
            name="youtube_url",
            field=models.URLField(max_length=500),
        ),
    ]
