# Generated by Django 5.2.9 on 2026-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_youtubelink_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubelink",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
