# Generated by Django 5.2.9 on 2026-03-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_youtubelink_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="avatar_url_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
