# Generated by Django 5.2.9 on 2026-03-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_users_avatar_url_users_avatar_url_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="address",
        ),
    ]
