# Generated by Django 5.2.9 on 2026-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_users_card_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image_url_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("priority", models.CharField(default="normal", max_length=20)),
            ],
        ),
    ]
