# Generated by Django 5.2.9 on 2026-03-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_youtubelink_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmodel",
            name="is_whatsapp",
            field=models.BooleanField(default=False),
        ),
    ]
