# Generated by Django 5.2.9 on 2026-03-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_supportmodel_is_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmodel",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
