# Generated by Django 5.2.9 on 2026-03-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_supportmodel_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmodel",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supportmodel",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
