# Generated by Django 5.2.9 on 2026-03-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_supportmodel_first_name_supportmodel_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportmodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
