# Generated by Django 5.2.9 on 2026-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_users_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="address_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
