# Generated by Django 5.2.9 on 2026-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_users_address_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="card_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
