# Generated by Django 5.2.9 on 2026-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_supportmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
