# Generated by Django 5.2.9 on 2026-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_supportmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubelink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("shorts", "Shorts"), ("review", "Review")],
                max_length=50,
                null=True,
            ),
        ),
    ]
