# Generated by Django 5.2.9 on 2026-03-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_youtubelink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubelink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("lesson", "Lesson"), ("think", "Think")],
                max_length=50,
                null=True,
            ),
        ),
    ]
