# Generated by Django 5.2.9 on 2026-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_digitalproduct_download_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalproductorder",
            name="refund_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="digitalproductorder",
            name="refund_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="digitalproductorder",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "Talep Yok"),
                    ("pending", "Beklemede"),
                    ("approved", "Onaylandı"),
                    ("rejected", "Reddedildi"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="digitalproductorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ödeme Bekliyor"),
                    ("completed", "Tamamlandı"),
                    ("failed", "Hatalı"),
                    ("refunded", "İade Edildi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
