# Generated by Django 5.2.9 on 2026-03-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_digitalproductcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.digitalproductcategory",
            ),
        ),
    ]
