# Generated by Django 5.2.9 on 2026-02-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogviewcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogviewcount",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
