# Generated by Django 5.2.9 on 2026-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogviewcount_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
