# Generated by Django 5.2.9 on 2026-02-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_category_tag_blogpost_category_blogpost_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="category",
        ),
    ]
