# Generated by Django 5.2.9 on 2026-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_levelexam_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ödeme Bekliyor"),
                    ("completed", "Tamamlandı"),
                    ("failed", "Hatalı"),
                    ("refund_requested", "İade Talep Edildi"),
                    ("refunded", "İade Edildi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
