# Generated by Django 5.2.9 on 2026-03-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_courseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="first_day",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="last_day",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
