# Generated by Django 5.2.9 on 2026-03-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_privatelesson_privatelessonorder_privatelessontag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatelessonorder",
            name="private_lesson",
        ),
        migrations.RemoveField(
            model_name="privatelessontag",
            name="private_lesson",
        ),
        migrations.RemoveField(
            model_name="privatelessonorder",
            name="user",
        ),
        migrations.AddField(
            model_name="course",
            name="is_private_lesson",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PrivateLesson",
        ),
        migrations.DeleteModel(
            name="PrivateLessonTag",
        ),
        migrations.DeleteModel(
            name="PrivateLessonOrder",
        ),
    ]
