# Generated by Django 5.2.9 on 2026-03-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalproduct",
            name="download_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="digitalproduct",
            name="external_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="digitalproduct",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="digital_products/"
            ),
        ),
        migrations.AddField(
            model_name="digitalproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("file", "Dosya (PDF/Kitap)"),
                    ("link", "Dış Bağlantı (Drive/Zoom)"),
                    ("manual", "Manuel Kayıt (Classroom)"),
                ],
                default="file",
                max_length=10,
            ),
        ),
    ]
